--script
local reps = game:GetService("ReplicatedStorage")
local workspace = game:GetService("Workspace")
local players = game:GetService("Players")
local Globals = require(reps.Globals)
local fcore = require(reps.funcs_core)
local fcommon = require(reps.funcs_common)
local detector = Instance.new("ClickDetector", workspace.Car)
players.PlayerAdded:Connect(fcore.on_player_added)
detector.MouseClick:Connect(fcommon.send_clicks)
